CC = gcc

.BUILD: start test_insertionSort clean

TEST: 
	./bin/insertionSortTest

get-deps:
	curl -O https://s3.amazonaws.com/CLibraries/CUnit-2.1-2-src.tar.bz2
	tar xjf CUnit-2.1-2-src.tar.bz2
	cd CUnit-2.1-2 && ./configure --prefix $(HOME)/local && make clean && make && make install
	rm CUnit-2.1-2-src.tar.bz2
	rm -r CUnit-2.1-2

test_insertionSort: ./tests/test_insertionSort.c dynarray.o insertionSort.o
	$(CC) -Wall -I$(HOME)/local/include ./tests/test_insertionSort.c dynarray.o insertionSort.o -L$(HOME)/local/lib -lcunit -o ./bin/insertionSortTest 

dynarray.o: ./src/libs/dynarray.c
	$(CC) -c ./src/libs/dynarray.c

insertionSort.o: ./src/sort/insertionSort.c
	$(CC) -c ./src/sort/insertionSort.c

start:
	mkdir -p bin

clean:
	rm *.o