CC = gcc

.TESTS: insertionSort clean

insertionSort: dynarray.o insertionSort.o test_insertionSort.o
	$(CC) dynarray.o insertionSort.o test_insertionSort.o -o ./bin/insertionSortTest

test_insertionSort.o: ./tests/test_insertionSort.c
	$(CC) -c ./tests/test_insertionSort.c

dynarray.o: ./libs/dynarray.c
	$(CC) -c ./libs/dynarray.c

insertionSort.o: ./sort/insertionSort.c
	$(CC) -c ./sort/insertionSort.c

start:
	mkdir bin

clean:
	rm *.o